# Generated by Django 4.2.2 on 2023-08-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketScan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentNumber', models.CharField(max_length=15)),
                ('incidentAddDetail', models.CharField(max_length=125)),
                ('incidentShow', models.BooleanField(default=True)),
                ('incidentResolutionPath', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.resolutionpath')),
            ],
        ),
    ]
