# Generated by Django 4.2.2 on 2023-08-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResolves',
            fields=[
                ('feedbackIncident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ticketView.incidentsolve')),
                ('feedbackResult', models.BooleanField(default=True)),
                ('feedbackDetail', models.CharField(blank=True, max_length=256, null=True)),
                ('feedbackShow', models.BooleanField(default=False)),
            ],
        ),
    ]
