# Generated by Django 4.2.2 on 2023-08-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorDetail', models.CharField(max_length=255)),
                ('fkAreaName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.problemarea')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentSuggestion', models.CharField(max_length=125)),
                ('incidentJustification', models.CharField(max_length=255)),
                ('incidentArea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.problemarea')),
                ('incidentDetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.problemerror')),
                ('incidentType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.problemplatform')),
            ],
        ),
        migrations.AddField(
            model_name='problemarea',
            name='fkPlatformName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketScan.problemplatform'),
        ),
    ]
